config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/index' => 'home#index'
  root :to =>  'home#index'
  get '/messages/:id/respond' => "messages#respond", as: "message_respond"
  resources :users
  resources :messages
  post '/message' => "messages#respond_create"
  resources :boards do
    resources :posts
    get 'posts/:id/edit_ajax' => "posts#edit_ajax", as: "post_edit_ajax"
  end
  resources :user_to_boards
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :title, :description, :sender_id, :receiver_id
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!
  def index
    @messages = Message.all.where(:parent_id => nil)
  end

  def show
    @message = Message.find(params[:id])
    @messages = Message.all.where(:parent_id => params[:id])
  end

  def new
    @message = Message.new
  end

  def respond
    @respond_message = Message.find(params[:id])
    @message = Message.new
  end

  def respond_create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_path(@message.parent_id), notice: 'message was successfully created.' }
        format.json { render action: 'show', status: :created}
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_path(@message), notice: 'message was successfully created.' }
        format.json { render action: 'show', status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to messages_path, notice: 'message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:title, :description, :sender_id, :receiver_id, :parent_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2
        = pluralize(@message.errors.count, "error")
        prohibited this advert from being saved:
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title, :title
    = f.text_field :title, class: "form-control", placeholder: "New message"
  %p
    = f.label :description
    = f.text_area :description, class: "form-control", placeholder: "123..."
  %p
    = f.label :receiver_id
    = f.select :receiver_id, options_from_collection_for_select(User.all, :id, :email)
  %p
    = f.hidden_field :sender_id, value: current_user.id
    = f.submit class: "btn btn-primary"

app/views/messages/index.html.haml
%h1 Wiadomosci
.table-responsive
  %table.table
    %tr
      %th.text-center #
      %th.text-center Tytuł
      %th.text-center Opis
      %th.text-center Nadawca
      %th.text-center Odbiorca
      %th.text-center Akcja
    - @messages.each do |message|
      %tr
        %td.text-center= message.id
        %td.text-center= message.title
        %td.text-center= message.description
        %td.text-center= message.sender_id
        %td.text-center= message.receiver_id
        %td.text-center
          .btn-group
            =link_to "Show", message_path(message), class:'btn btn-info'
            =link_to "Edit", edit_user_registration_path(message), class:'btn btn-default'
            =link_to "Destroy", message, data: {method: :delete, confirm: "Jesteś pewien?"}, class:'btn btn-danger'

=link_to "New", new_message_path, class:"btn btn-info"

app/views/messages/new.html.haml
%h1 Nowa wiadomosc
=render "form"
=link_to "Back", :back, class: "btn btn-info"

app/views/messages/respond.html.haml
= form_for @message, :url => {:controller => :messages, :action => :respond_create} do |f|
  - if @message.errors.any?
    #error_explanation
      %h2
        = pluralize(@message.errors.count, "error")
        prohibited this advert from being saved:
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.hidden_field :title, value: @respond_message.title
  %p
    = f.label :description
    = f.text_area :description, class: "form-control", placeholder: "123..."

  %p
    = f.hidden_field :receiver_id, value: @respond_message.sender_id
    = f.hidden_field :parent_id, value: @respond_message.id
    = f.hidden_field :sender_id, value: current_user.id
    = f.submit class: "btn btn-primary"

app/views/messages/show.html.haml
%h1
  Wiadomosci
.panel.panel-primary
  .panel-heading
    .panel-title
      =@message.title
  .panel-body
    =@message.description
-@messages.each do |message|
  .panel.panel-primary
    .panel-heading
      .panel-title
        =@message.title
    .panel-body
      =message.description
=link_to "Odpowiedz", message_respond_path(@message), class:"btn btn-info"