config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/index' => 'home#index'
  root :to =>  'home#index'
  get '/messages/:id/respond' => "messages#respond", as: "message_respond"
  resources :users
  resources :messages
  post '/message' => "messages#respond_create"
  resources :boards do
    resources :posts
    get 'posts/:id/edit_ajax' => "posts#edit_ajax", as: "post_edit_ajax"
  end
  resources :user_to_boards
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates_presence_of :title
  
  has_many :posts

  has_many :user_to_boards, dependent: :destroy
  has_many :users, through: :user_to_boards
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
    authorize @board
  end

  def create
    @board = Board.new(board_params)
    authorize @board
    respond_to do |format|
      if @board.save
        format.html { redirect_to board_posts_path(@board), notice: 'board was successfully created.' }
        format.json { render action: 'show', status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @board
  end

  def update
    authorize @board
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to boards_path, notice: 'board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @board
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_path }
      format.json { head :no_content }
    end
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:title)
    end
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      %h2
        = pluralize(@board.errors.count, "error")
        prohibited this advert from being saved:
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title, :title
    = f.text_field :title, class: "form-control", placeholder: "New board"
  %p
    = f.submit class: "btn btn-primary"

app/views/boards/edit.html.haml
%h1 Edytuj Forum
=render "form"
=link_to "Back", :back, class: "btn btn-info"

app/views/boards/index.html.haml
%h1 Forum
.table-responsive
  %table.table
    %tr
      %th.text-center #
      %th.text-center Tytuł
      %th.text-center Akcja
    - @boards.each do |board|
      -if policy(board).index?
        %tr
          %td.text-center= board.id
          %td.text-center= board.title
          %td.text-center
            .btn-group
              =link_to "Show", board_posts_path(board), class:'btn btn-info'
              =link_to "Edit", edit_board_path(board), class:'btn btn-default'
              =link_to "Destroy", board, data: {method: :delete, confirm: "Jesteś pewien?"}, class:'btn btn-danger'
=link_to "New", new_board_path, class:'btn btn-primary'

app/views/boards/new.html.haml
%h1 Nowe Forum
=render "form"
=link_to "Back", :back, class: "btn btn-info"

app/views/boards/show.html.haml
%h1
  =@board.title
.table-responsive
  %table.table
    %tr
      %th.text-center #
    - @posts.each do |post|
      %tr
        %td.text-center=link_to post.title, board_post_path(@board, post.id)


  =link_to "Nowy post", new_board_post_path(@board), class:"btn btn-primary"
  =link_to "Back", :back, class:"btn btn-info"