config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/index' => 'home#index'
  root :to =>  'home#index'
  get '/messages/:id/respond' => "messages#respond", as: "message_respond"
  resources :users
  resources :messages
  post '/message' => "messages#respond_create"
  resources :boards do
    resources :posts
    get 'posts/:id/edit_ajax' => "posts#edit_ajax", as: "post_edit_ajax"
  end
  resources :user_to_boards
end

app/views/layouts/_header.html.haml
.navbar.navbar-inverse
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      FOKI JEZE MOKRE DOLARY
  .navbar-collapse.collapse
    %ul.nav.navbar-nav.navbar-right
      %li=link_to "Forum", boards_path
      %li
        =link_to users_path do
          %span.glyphicon.glyphicon-briefcase
          Konto
      %li
        =link_to messages_path do
          %span.glyphicon.glyphicon-envelope
          Wiadomosci
      -if user_signed_in?
        %li= link_to 'Edytuj Profil', edit_user_registration_path, class:'btn'
        %li= link_to "Logout", destroy_user_session_path, method: :delete, class:'btn'
      -else
        %li
          =link_to new_user_registration_path do
            %span.glyphicon.glyphicon-user
            Zarejestruj
        %li
          =link_to new_user_session_path do
            %span.glyphicon.glyphicon-log-in
            Zaloguj

app/views/layouts/application.html.haml
%html
  %head
    %title Forum
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    =render 'layouts/header'
    .container
      -flash.each do |key, value|
        %div{:class => "alert alert-#{key}" }= value
      = yield
    .footer
      %hr
        %p Za Kabone z prodewenta @ Created by xG & Powered by Ruby <3